---
version: "2.0"

services:
  desmos:
    image: paullovette/desmos_on_akash_v001
    env:
      # - STATE_SYNC=1
      - SEEDS_URL=https://raw.githubusercontent.com/lightiv/akash-on-akash/desmos/seed-nodes.txt
      - SYNC_URL=https://raw.githubusercontent.com/lightiv/akash-on-akash/desmos/rpc-nodes.txt
      - GENESIS_URL=https://raw.githubusercontent.com/desmos-labs/morpheus/master/morpheus-13001/genesis.json
      - ENABLE_ID_SERVER=true
      # - DESMOS_PRUNING=custom
      # - DESMOS_PRUNING_INTERVAL=10
      # - DESMOS_PRUNING_KEEP_EVERY=50
      # - DESMOS_PRUNING_KEEP_RECENT=10
      # - DESMOS_STATE_SYNC_SNAPSHOT_INTERVAL=50
      # - DESMOS_STATE_SYNC_KEEP_RECENT=10
      # - DESMOS_SEED_MODE=true
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 9090
        to:
          - global: true

profiles:
  compute:
    akash:
      resources:
        cpu:
          units: 1
        memory:
          size: 8Gi
        storage:
          size: 128Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        akash:
          denom: uakt
          amount: 100

deployment:
  akash:
    dcloud:
      profile: akash
      count: 1
